"""initial migration v2

Revision ID: 38c5fa2a20af
Revises: 909cf6558bf1
Create Date: 2026-04-10 20:02:57.868717

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "38c5fa2a20af"
down_revision: str | Sequence[str] | None = "909cf6558bf1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Countries",
        sa.Column("Id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("CountryCode", sa.Integer(), nullable=False),
        sa.Column("CountryName", sa.String(length=255), nullable=False),
        sa.Column("Alpha2", sa.String(length=2), nullable=False),
        sa.Column("Alpha3", sa.String(length=3), nullable=False),
        sa.PrimaryKeyConstraint("Id", name=op.f("pk_Countries")),
        sa.UniqueConstraint("Alpha2", name=op.f("uq_Countries_Alpha2")),
        sa.UniqueConstraint("Alpha3", name=op.f("uq_Countries_Alpha3")),
        sa.UniqueConstraint("CountryCode", name=op.f("uq_Countries_CountryCode")),
        sa.UniqueConstraint("CountryName", name=op.f("uq_Countries_CountryName")),
    )
    op.create_table(
        "OrganisationSize",
        sa.Column("OrganisationSizeCode", sa.Integer(), nullable=False),
        sa.Column("OrganisationSizeDescription", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("OrganisationSizeCode", name=op.f("pk_OrganisationSize")),
        sa.UniqueConstraint(
            "OrganisationSizeDescription", name=op.f("uq_OrganisationSize_OrganisationSizeDescription")
        ),
    )
    op.create_table(
        "PartnerType",
        sa.Column("PartnerTypeCode", sa.Integer(), nullable=False),
        sa.Column("PartnerTypeCodeDescription", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("PartnerTypeCode", name=op.f("pk_PartnerType")),
    )
    op.create_table(
        "Party",
        sa.Column("PartyIdentifier", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("PartyIdentifier", name=op.f("pk_Party")),
    )
    op.create_table(
        "CategoryTypes",
        sa.Column("CategoryCode", sa.Integer(), nullable=False),
        sa.Column("PartnerTypeCode", sa.Integer(), nullable=True),
        sa.Column("CategoryDescription", sa.String(length=1000), nullable=False),
        sa.ForeignKeyConstraint(
            ["PartnerTypeCode"],
            ["PartnerType.PartnerTypeCode"],
            name=op.f("fk_CategoryTypes_PartnerTypeCode_PartnerType"),
        ),
        sa.PrimaryKeyConstraint("CategoryCode", name=op.f("pk_CategoryTypes")),
        sa.UniqueConstraint("CategoryDescription", name=op.f("uq_CategoryTypes_CategoryDescription")),
    )
    op.create_table(
        "Organisations",
        sa.Column("OrganisationId", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("CountryId", sa.Integer(), nullable=True),
        sa.Column("CategoryTypeCode", sa.Integer(), nullable=True),
        sa.Column("PartnerTypeCode", sa.Integer(), nullable=True),
        sa.Column("PartyIdentifier", sa.Integer(), nullable=True),
        sa.Column("OrganisationSizeCode", sa.Integer(), nullable=True),
        sa.Column("OrganisationName", sa.String(length=1000), nullable=False),
        sa.Column("OrganisationRegistrationNumber", sa.String(length=50), nullable=True),
        sa.Column("RegionName", sa.String(length=500), nullable=True),
        sa.Column("AddressLine1Description", sa.String(length=1000), nullable=True),
        sa.Column("CityName", sa.String(length=500), nullable=True),
        sa.Column("StateName", sa.String(length=500), nullable=True),
        sa.Column("WebsiteUrl", sa.String(length=500), nullable=True),
        sa.Column("SustainabilityUrl", sa.String(length=500), nullable=True),
        sa.Column("PrimaryEmailAddress", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["CategoryTypeCode"],
            ["CategoryTypes.CategoryCode"],
            name=op.f("fk_Organisations_CategoryTypeCode_CategoryTypes"),
        ),
        sa.ForeignKeyConstraint(
            ["CountryId"], ["Countries.Id"], name=op.f("fk_Organisations_CountryId_Countries")
        ),
        sa.ForeignKeyConstraint(
            ["OrganisationSizeCode"],
            ["OrganisationSize.OrganisationSizeCode"],
            name=op.f("fk_Organisations_OrganisationSizeCode_OrganisationSize"),
        ),
        sa.ForeignKeyConstraint(
            ["PartnerTypeCode"],
            ["PartnerType.PartnerTypeCode"],
            name=op.f("fk_Organisations_PartnerTypeCode_PartnerType"),
        ),
        sa.ForeignKeyConstraint(
            ["PartyIdentifier"],
            ["Party.PartyIdentifier"],
            name=op.f("fk_Organisations_PartyIdentifier_Party"),
        ),
        sa.PrimaryKeyConstraint("OrganisationId", name=op.f("pk_Organisations")),
        sa.UniqueConstraint("OrganisationId", name=op.f("uq_Organisations_OrganisationId")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Organisations")
    op.drop_table("CategoryTypes")
    op.drop_table("Party")
    op.drop_table("PartnerType")
    op.drop_table("OrganisationSize")
    op.drop_table("Countries")
    # ### end Alembic commands ###
