"""initial migration v1

Revision ID: 909cf6558bf1
Revises: 3a4d7a3dbd50
Create Date: 2026-04-10 19:52:43.423272

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "909cf6558bf1"
down_revision: str | Sequence[str] | None = "3a4d7a3dbd50"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
